title: Hyperreal | Jordan B. Peterson
project_name: Hyperreal
description: >
  From the Lectures of Jordan B. Peterson
repository_url: https://github.com/vsinha/hyperreal
repository_shorthand: vsinha/hyperreal

production_url: hyperreal.vsinha.com

author_name: viraj sinha
author_url: https://github.com/vsinha

markdown: kramdown
